In [1]:
import pandas as pd
import numpy as np
import optuna
from sklearn.metrics import roc_auc_score
import catboost as cb

In [2]:
df_cat = pd.read_csv('df_cat.csv')
df_cat.head()

,age,workclass,education,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,Private,HS-grad,Widowed,Prof-specialty,Not-in-family,White,Female,0.0,8.379539,40,United-States,<=50K
1,82,Private,HS-grad,Widowed,Exec-managerial,Not-in-family,White,Female,0.0,8.379539,18,United-States,<=50K
2,66,Private,Some-college,Widowed,Prof-specialty,Unmarried,Black,Female,0.0,8.379539,40,United-States,<=50K
3,54,Private,7th-8th,Divorced,Machine-op-inspct,Unmarried,White,Female,0.0,8.268988,40,United-States,<=50K
4,41,Private,Some-college,Separated,Prof-specialty,Own-child,White,Female,0.0,8.268988,40,United-States,<=50K

In [3]:
X = df_cat.drop('income', axis=1)
y = df_cat['income']
X.shape, y.shape

((32561, 12), (32561,))

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=19)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((22792, 12), (9769, 12), (22792,), (9769,))

In [5]:
df_cat_val = X_test.copy()
df_cat_val['target'] = y_test
df_cat_val.head()

,age,workclass,education,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,target
31966,27,Private,Some-college,Never-married,Other-service,Not-in-family,White,Female,0.0,0.0,34,United-States,<=50K
29138,34,Private,Some-college,Separated,Adm-clerical,Unmarried,Black,Female,0.0,0.0,40,Other,<=50K
26720,62,Local-gov,9th,Divorced,Protective-serv,Not-in-family,Black,Male,0.0,0.0,24,United-States,<=50K
8866,26,Private,HS-grad,Never-married,Craft-repair,Own-child,White,Male,0.0,0.0,35,United-States,<=50K
13002,39,Private,10th,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0.0,0.0,60,United-States,<=50K

In [6]:
df_cat_val.to_csv('df_cat_val.csv', index=False)

In [8]:
target = y.value_counts()
res = target.iloc[0] / target.iloc[1]
print(f'Target disbalance: {res:.3f}')

Target disbalance: 3.153

In [9]:
cat_features = ['workclass', 'education', 'marital.status', 'occupation', 'relationship', 'race',
               'sex', 'native.country']

In [13]:
def objective(trial):

    params = {

        'scale_pos_weight': res,
        
        'iterations': 1000,
        'learning_rate': trial.suggest_float('learning_rate', 1e-3, 0.1, log=True),
        'depth': trial.suggest_int('depth', 4, 10),
        'l2_leaf_reg': trial.suggest_float('l2_leaf_reg', 1e-8, 10.0, log=True),
        'bootstrap_type': 'MVS',
        'subsample': trial.suggest_float('subsample', 0.5, 1.0),
        'random_strength': trial.suggest_float('random_strength', 1e-8, 10.0, log=True),
        'od_type': 'Iter',
        'od_wait': 50,
        'verbose': False,
        'eval_metric': 'AUC',
        'random_state': 19,
    }

    X_t, X_v, y_t, y_v = train_test_split(X_train, y_train, test_size=0.2, random_state=19)

    model = cb.CatBoostClassifier(**params)
    
    model.fit(
        X_t, y_t,
        cat_features=cat_features,
        eval_set=(X_v, y_v),
        early_stopping_rounds=50
    )

    preds = model.predict_proba(X_v)[:, 1]
    roc_auc = roc_auc_score(y_v, preds)
    return roc_auc

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=40)

[I 2026-03-19 17:44:48,918] A new study created in memory with name: no-name-85a2098d-560f-43bb-b6b9-04e1f284f7cb
[I 2026-03-19 17:45:28,904] Trial 0 finished with value: 0.922686630712461 and parameters: {'learning_rate': 0.006379862586480066, 'depth': 4, 'l2_leaf_reg': 0.06538874506293232, 'subsample': 0.6639570265724569, 'random_strength': 4.097351996948309e-08}. Best is trial 0 with value: 0.922686630712461.
[I 2026-03-19 17:45:45,896] Trial 1 finished with value: 0.9267375065345546 and parameters: {'learning_rate': 0.06710454343318639, 'depth': 6, 'l2_leaf_reg': 3.936631906461959e-07, 'subsample': 0.7115159780013379, 'random_strength': 4.016361572368425}. Best is trial 1 with value: 0.9267375065345546.
[I 2026-03-19 17:47:13,519] Trial 2 finished with value: 0.9190193346097404 and parameters: {'learning_rate': 0.0024370349653439318, 'depth': 9, 'l2_leaf_reg': 8.494397716259544e-07, 'subsample': 0.8530158564138532, 'random_strength': 3.261540471280482e-08}. Best is trial 1 with value: 0.9267375065345546.
[I 2026-03-19 17:48:23,424] Trial 3 finished with value: 0.9173139117788562 and parameters: {'learning_rate': 0.00406254603463269, 'depth': 10, 'l2_leaf_reg': 2.6661177015971455e-05, 'subsample': 0.9501280572820872, 'random_strength': 2.9949554684309227e-05}. Best is trial 1 with value: 0.9267375065345546.
[I 2026-03-19 17:48:31,748] Trial 4 finished with value: 0.8974669491274657 and parameters: {'learning_rate': 0.0012910950787723093, 'depth': 10, 'l2_leaf_reg': 1.4884685208316095e-08, 'subsample': 0.8106868170565317, 'random_strength': 0.0005090673488885564}. Best is trial 1 with value: 0.9267375065345546.
[I 2026-03-19 17:48:36,812] Trial 5 finished with value: 0.8974599624968629 and parameters: {'learning_rate': 0.002434259209384112, 'depth': 8, 'l2_leaf_reg': 7.656644274042127e-07, 'subsample': 0.9585257889335019, 'random_strength': 9.450131936727883e-06}. Best is trial 1 with value: 0.9267375065345546.
[I 2026-03-19 17:49:42,077] Trial 6 finished with value: 0.9237577770788101 and parameters: {'learning_rate': 0.008075665109191549, 'depth': 8, 'l2_leaf_reg': 5.88261827163208e-06, 'subsample': 0.7075712172357831, 'random_strength': 0.0005594596123909001}. Best is trial 1 with value: 0.9267375065345546.
Training has stopped (degenerate solution on iteration 58, probably too small l2-regularization, try to increase it)
[I 2026-03-19 17:49:48,215] Trial 7 finished with value: 0.9175851574375559 and parameters: {'learning_rate': 0.06499593815352225, 'depth': 9, 'l2_leaf_reg': 1.4957249408208406e-07, 'subsample': 0.7286752524176505, 'random_strength': 4.1174018283081635e-05}. Best is trial 1 with value: 0.9267375065345546.
[I 2026-03-19 17:51:28,405] Trial 8 finished with value: 0.9229195183992231 and parameters: {'learning_rate': 0.0025908475813585627, 'depth': 9, 'l2_leaf_reg': 0.10169266167633774, 'subsample': 0.7581928261481954, 'random_strength': 1.6924761063716698e-08}. Best is trial 1 with value: 0.9267375065345546.
[I 2026-03-19 17:51:43,694] Trial 9 finished with value: 0.9156795881888133 and parameters: {'learning_rate': 0.07283792942878474, 'depth': 10, 'l2_leaf_reg': 4.722572655015806e-05, 'subsample': 0.9083982626424288, 'random_strength': 0.09736450667510609}. Best is trial 1 with value: 0.9267375065345546.
[I 2026-03-19 17:52:29,456] Trial 10 finished with value: 0.927443019232687 and parameters: {'learning_rate': 0.023885227824569897, 'depth': 6, 'l2_leaf_reg': 0.0022284424483129247, 'subsample': 0.526549462682124, 'random_strength': 4.793199994508896}. Best is trial 10 with value: 0.927443019232687.
[I 2026-03-19 17:53:19,091] Trial 11 finished with value: 0.9285138916135226 and parameters: {'learning_rate': 0.02661210165548812, 'depth': 5, 'l2_leaf_reg': 0.0021642595592021112, 'subsample': 0.5412193289400313, 'random_strength': 9.813396213505415}. Best is trial 11 with value: 0.9285138916135226.
[I 2026-03-19 17:54:17,922] Trial 12 finished with value: 0.9278583812716655 and parameters: {'learning_rate': 0.020261455937454046, 'depth': 5, 'l2_leaf_reg': 0.002002277049688457, 'subsample': 0.5506382467363078, 'random_strength': 6.590862126048729}. Best is trial 11 with value: 0.9285138916135226.
[I 2026-03-19 17:55:08,494] Trial 13 finished with value: 0.9295047602243174 and parameters: {'learning_rate': 0.022172895478994845, 'depth': 4, 'l2_leaf_reg': 0.0019445029163544026, 'subsample': 0.5019863453494742, 'random_strength': 0.07143726229129845}. Best is trial 13 with value: 0.9295047602243174.
[I 2026-03-19 17:56:03,863] Trial 14 finished with value: 0.9282585371146257 and parameters: {'learning_rate': 0.02338121208275734, 'depth': 4, 'l2_leaf_reg': 1.033686648414972, 'subsample': 0.5976139786468257, 'random_strength': 0.03273942770010075}. Best is trial 13 with value: 0.9295047602243174.
[I 2026-03-19 17:57:08,465] Trial 15 finished with value: 0.9286460896239493 and parameters: {'learning_rate': 0.013813831057415772, 'depth': 5, 'l2_leaf_reg': 0.001066904312895408, 'subsample': 0.5010392370424015, 'random_strength': 0.13190095992609852}. Best is trial 13 with value: 0.9295047602243174.
[I 2026-03-19 17:58:14,222] Trial 16 finished with value: 0.9256829362917923 and parameters: {'learning_rate': 0.012172136581144296, 'depth': 5, 'l2_leaf_reg': 8.50208037651369, 'subsample': 0.6262554002748771, 'random_strength': 0.04457133938142821}. Best is trial 13 with value: 0.9295047602243174.
[I 2026-03-19 17:58:37,680] Trial 17 finished with value: 0.9281270240679835 and parameters: {'learning_rate': 0.03915294551618869, 'depth': 6, 'l2_leaf_reg': 0.03455596685452087, 'subsample': 0.5091207689900443, 'random_strength': 0.006622553585285247}. Best is trial 13 with value: 0.9295047602243174.
[I 2026-03-19 17:59:27,229] Trial 18 finished with value: 0.9279794828687818 and parameters: {'learning_rate': 0.015234715807624892, 'depth': 4, 'l2_leaf_reg': 0.00024026835694007347, 'subsample': 0.597640246411312, 'random_strength': 0.16537279540635122}. Best is trial 13 with value: 0.9295047602243174.
[I 2026-03-19 17:59:50,165] Trial 19 finished with value: 0.9240147754907904 and parameters: {'learning_rate': 0.045511997754630246, 'depth': 7, 'l2_leaf_reg': 0.00028065814348171407, 'subsample': 0.5748208210775256, 'random_strength': 0.5378510947243399}. Best is trial 13 with value: 0.9295047602243174.
[I 2026-03-19 18:00:55,102] Trial 20 finished with value: 0.9248560480110294 and parameters: {'learning_rate': 0.006298024847157879, 'depth': 5, 'l2_leaf_reg': 0.0036419003842406554, 'subsample': 0.5005879182839328, 'random_strength': 0.0036375283145854537}. Best is trial 13 with value: 0.9295047602243174.
[I 2026-03-19 18:01:39,629] Trial 21 finished with value: 0.9293829736634165 and parameters: {'learning_rate': 0.035413766731297654, 'depth': 5, 'l2_leaf_reg': 0.00960373678582437, 'subsample': 0.641104282870025, 'random_strength': 0.6445504865881923}. Best is trial 13 with value: 0.9295047602243174.
[I 2026-03-19 18:02:16,874] Trial 22 finished with value: 0.9285107407801134 and parameters: {'learning_rate': 0.03536588382746884, 'depth': 4, 'l2_leaf_reg': 0.015160672361079135, 'subsample': 0.612873422859321, 'random_strength': 0.6809288037196163}. Best is trial 13 with value: 0.9295047602243174.
[I 2026-03-19 18:03:01,166] Trial 23 finished with value: 0.9273478092666284 and parameters: {'learning_rate': 0.015051221541105974, 'depth': 5, 'l2_leaf_reg': 0.7584813092973758, 'subsample': 0.6591215926042737, 'random_strength': 0.006068703194494473}. Best is trial 13 with value: 0.9295047602243174.
[I 2026-03-19 18:04:15,395] Trial 24 finished with value: 0.9240332695129744 and parameters: {'learning_rate': 0.009883041593882565, 'depth': 6, 'l2_leaf_reg': 7.020820011943142e-05, 'subsample': 0.6632668582800358, 'random_strength': 0.731672717476501}. Best is trial 13 with value: 0.9295047602243174.
[I 2026-03-19 18:04:33,708] Trial 25 finished with value: 0.9271032771955281 and parameters: {'learning_rate': 0.04595197498297587, 'depth': 7, 'l2_leaf_reg': 0.01182555113534138, 'subsample': 0.5635792644884766, 'random_strength': 0.013846673116562761}. Best is trial 13 with value: 0.9295047602243174.
[I 2026-03-19 18:04:50,637] Trial 26 finished with value: 0.9279824967094339 and parameters: {'learning_rate': 0.09629899146618832, 'depth': 4, 'l2_leaf_reg': 0.272995773107013, 'subsample': 0.5655194871076139, 'random_strength': 0.26378417840743734}. Best is trial 13 with value: 0.9295047602243174.
[I 2026-03-19 18:05:57,664] Trial 27 finished with value: 0.9294783206222321 and parameters: {'learning_rate': 0.01568008668136872, 'depth': 5, 'l2_leaf_reg': 0.0008328673850942279, 'subsample': 0.78392928391905, 'random_strength': 0.001460189945337834}. Best is trial 13 with value: 0.9295047602243174.
[I 2026-03-19 18:06:25,006] Trial 28 finished with value: 0.928119352473596 and parameters: {'learning_rate': 0.029941136210090157, 'depth': 6, 'l2_leaf_reg': 7.493547535475374e-06, 'subsample': 0.794788413085862, 'random_strength': 0.0018691083568482534}. Best is trial 13 with value: 0.9295047602243174.
[I 2026-03-19 18:07:18,850] Trial 29 finished with value: 0.9292918734800655 and parameters: {'learning_rate': 0.01862375651917902, 'depth': 4, 'l2_leaf_reg': 0.00039140494684741366, 'subsample': 0.8672429938236593, 'random_strength': 5.322234291399354e-07}. Best is trial 13 with value: 0.9295047602243174.
[I 2026-03-19 18:08:13,568] Trial 30 finished with value: 0.9219265948970746 and parameters: {'learning_rate': 0.005901440145995372, 'depth': 4, 'l2_leaf_reg': 0.018312886906076385, 'subsample': 0.7720569609281198, 'random_strength': 0.00011129859010150785}. Best is trial 13 with value: 0.9295047602243174.
[I 2026-03-19 18:09:11,644] Trial 31 finished with value: 0.929157346592771 and parameters: {'learning_rate': 0.01836170009644603, 'depth': 4, 'l2_leaf_reg': 0.0004536081651077633, 'subsample': 0.8508615475410277, 'random_strength': 1.1823803412611835e-06}. Best is trial 13 with value: 0.9295047602243174.
[I 2026-03-19 18:10:08,648] Trial 32 finished with value: 0.9294007827218159 and parameters: {'learning_rate': 0.01868776931018428, 'depth': 4, 'l2_leaf_reg': 0.007009486768156478, 'subsample': 0.869351842088608, 'random_strength': 1.697396324907977e-07}. Best is trial 13 with value: 0.9295047602243174.
[I 2026-03-19 18:11:13,282] Trial 33 finished with value: 0.9273764407528244 and parameters: {'learning_rate': 0.008755059997479466, 'depth': 5, 'l2_leaf_reg': 0.007366508934933276, 'subsample': 0.6971621295841419, 'random_strength': 1.4390783448032658e-07}. Best is trial 13 with value: 0.9295047602243174.
[I 2026-03-19 18:11:48,925] Trial 34 finished with value: 0.9291311809761995 and parameters: {'learning_rate': 0.0523164752356577, 'depth': 4, 'l2_leaf_reg': 0.08276723769802248, 'subsample': 0.9004086177111694, 'random_strength': 1.713041778540211}. Best is trial 13 with value: 0.9295047602243174.
[I 2026-03-19 18:12:31,822] Trial 35 finished with value: 0.9290107643428677 and parameters: {'learning_rate': 0.03012984608792687, 'depth': 5, 'l2_leaf_reg': 0.006086244005408347, 'subsample': 0.8120332307427325, 'random_strength': 4.008354275213992e-06}. Best is trial 13 with value: 0.9295047602243174.
[I 2026-03-19 18:12:56,863] Trial 36 finished with value: 0.9277753636609725 and parameters: {'learning_rate': 0.03319799171646187, 'depth': 6, 'l2_leaf_reg': 8.844400774954643e-05, 'subsample': 0.8400697389064662, 'random_strength': 0.027990164222790666}. Best is trial 13 with value: 0.9295047602243174.
[I 2026-03-19 18:13:47,819] Trial 37 finished with value: 0.9257847219101832 and parameters: {'learning_rate': 0.011760946465771584, 'depth': 7, 'l2_leaf_reg': 1.2270905485816713e-05, 'subsample': 0.9192265917376686, 'random_strength': 0.0008986703017643786}. Best is trial 13 with value: 0.9295047602243174.
[I 2026-03-19 18:14:38,744] Trial 38 finished with value: 0.9191885206645355 and parameters: {'learning_rate': 0.00471933430047693, 'depth': 4, 'l2_leaf_reg': 0.04032257407490737, 'subsample': 0.9784510731978607, 'random_strength': 7.986494991911133e-05}. Best is trial 13 with value: 0.9295047602243174.
[I 2026-03-19 18:15:36,141] Trial 39 finished with value: 0.910847442674011 and parameters: {'learning_rate': 0.001183989245341195, 'depth': 5, 'l2_leaf_reg': 0.1373571904831197, 'subsample': 0.7329586227227622, 'random_strength': 0.00014599414416544392}. Best is trial 13 with value: 0.9295047602243174.

In [14]:
best_params = study.best_params
best_params

{'learning_rate': 0.022172895478994845,
 'depth': 4,
 'l2_leaf_reg': 0.0019445029163544026,
 'subsample': 0.5019863453494742,
 'random_strength': 0.07143726229129845}

In [15]:
print(f'ROC AUC score :{study.best_value:.4f}')

ROC AUC score :0.9295

In [16]:
cat_model = cb.CatBoostClassifier(**best_params, random_state=19)

In [19]:
cat_model.fit(X_train, y_train, cat_features=cat_features, verbose=0)

In [20]:
import joblib
joblib.dump(cat_model, 'cat_model.joblib')

['cat_model.joblib']