In [1]:
import pandas as pd
import numpy as np
import optuna
from sklearn.metrics import roc_auc_score
import xgboost as xgb

In [4]:
df_xgb = pd.read_csv('df_enc_xgb.csv')

In [5]:
df_xgb.head()

,age,workclass,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,3.769612,0.210093,-0.420060,0.085599,0.342637,0.103070,0.25586,0.109461,0.0,8.379539,-0.035429,0.245835,0
1,3.183112,0.210093,-0.420060,0.085599,0.484014,0.103070,0.25586,0.109461,0.0,8.379539,-1.817204,0.245835,0
2,2.010110,0.210093,-0.031360,0.085599,0.342637,0.063262,0.12388,0.109461,0.0,8.379539,-0.035429,0.245835,0
3,1.130359,0.210093,-2.363558,0.104209,0.124875,0.063262,0.25586,0.109461,0.0,8.268988,-0.035429,0.245835,0
4,0.177296,0.210093,-0.031360,0.064390,0.342637,0.013220,0.25586,0.109461,0.0,8.268988,-0.035429,0.245835,0

In [6]:
X = df_xgb.drop('income', axis=1)
y = df_xgb['income']
X.shape, y.shape

((32561, 12), (32561,))

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=19)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((22792, 12), (9769, 12), (22792,), (9769,))

In [31]:
df_xgb_val = X_test.copy()
df_xgb_val['target'] = y_test
df_xgb_val.head()

,age,workclass,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,target
31966,-0.849080,0.210093,-0.031360,0.045961,0.041578,0.103070,0.25586,0.109461,0.0,0.0,-0.521368,0.245835,0
29138,-0.335892,0.210093,-0.031360,0.064390,0.134483,0.063262,0.12388,0.109461,0.0,0.0,-0.035429,0.250429,0
26720,1.716860,0.294792,-1.974858,0.104209,0.325116,0.103070,0.12388,0.305737,0.0,0.0,-1.331266,0.245835,0
8866,-0.922393,0.210093,-0.420060,0.045961,0.226641,0.013220,0.25586,0.305737,0.0,0.0,-0.440378,0.245835,0
13002,0.030671,0.210093,-1.586158,0.446848,0.124875,0.448571,0.25586,0.305737,0.0,0.0,1.584366,0.245835,0

In [32]:
df_xgb_val.to_csv('df_xgb_val.csv', index=False)

In [33]:
target = y.value_counts()
res = target[0] / target[1]
print(f'Target disbalance: {res:.3f}')

Target disbalance: 3.153

In [34]:
def objective(trial):

    params = {
        'scale_pos_weight': res,

        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'subsample': trial.suggest_float('subsample', 0.5, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
        'reg_alpha': trial.suggest_float('reg_alpha', 1e-8, 10.0, log=True),
        'reg_lambda': trial.suggest_float('reg_lambda', 1e-8, 10.0, log=True),

        'n_estimators': 2000,
        'early_stopping_rounds': 50,
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'max_depth': trial.suggest_int('max_depth', 3, 8),
        'eval_metric': 'auc',
        'random_state': 4,
        'verbosity': 0,
        'nthread': -1
    }

    X_t, X_v, y_t, y_v = train_test_split(X_train, y_train, test_size=0.2, random_state=19)

    model = xgb.XGBClassifier(**params)
    model.fit(
    X_t, y_t,
    eval_set=[(X_v, y_v)],
    verbose=False
    )
    y_pred = model.predict_proba(X_v)[:, 1]
    roc_auc = roc_auc_score(y_v, y_pred)

    return roc_auc

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=40)

[I 2026-03-19 17:24:28,408] A new study created in memory with name: no-name-dd65276d-278d-4417-a379-c107bc3a4079
[I 2026-03-19 17:24:28,650] Trial 0 finished with value: 0.9292037871373665 and parameters: {'min_child_weight': 7, 'subsample': 0.9118587087745963, 'colsample_bytree': 0.5776817878622502, 'reg_alpha': 0.023687910225859293, 'reg_lambda': 0.00040052056757459775, 'learning_rate': 0.1823388081995549, 'max_depth': 4}. Best is trial 0 with value: 0.9292037871373665.
[I 2026-03-19 17:24:28,841] Trial 1 finished with value: 0.9292752973564781 and parameters: {'min_child_weight': 3, 'subsample': 0.870249353826001, 'colsample_bytree': 0.5316718877964837, 'reg_alpha': 0.000274871513497801, 'reg_lambda': 0.00356842842968086, 'learning_rate': 0.13636705851770073, 'max_depth': 8}. Best is trial 1 with value: 0.9292752973564781.
[I 2026-03-19 17:24:29,076] Trial 2 finished with value: 0.9295424332324701 and parameters: {'min_child_weight': 6, 'subsample': 0.9607139708447725, 'colsample_bytree': 0.7179200552708211, 'reg_alpha': 4.7021345915597514e-08, 'reg_lambda': 0.00587297462187021, 'learning_rate': 0.08213597047383164, 'max_depth': 6}. Best is trial 2 with value: 0.9295424332324701.
[I 2026-03-19 17:24:29,176] Trial 3 finished with value: 0.9137388118015424 and parameters: {'min_child_weight': 6, 'subsample': 0.8749782490655862, 'colsample_bytree': 0.8175662387898943, 'reg_alpha': 4.310050505211038e-07, 'reg_lambda': 0.0009433578263270272, 'learning_rate': 0.010749235376325857, 'max_depth': 5}. Best is trial 2 with value: 0.9295424332324701.
[I 2026-03-19 17:24:29,529] Trial 4 finished with value: 0.9298084731664067 and parameters: {'min_child_weight': 5, 'subsample': 0.8434093181749618, 'colsample_bytree': 0.6480260447469417, 'reg_alpha': 0.017805107733651404, 'reg_lambda': 1.3465405912015038e-06, 'learning_rate': 0.060629775514620315, 'max_depth': 5}. Best is trial 4 with value: 0.9298084731664067.
[I 2026-03-19 17:24:30,236] Trial 5 finished with value: 0.9273117801715588 and parameters: {'min_child_weight': 4, 'subsample': 0.7236762793065165, 'colsample_bytree': 0.6829440535317934, 'reg_alpha': 2.2969682128474114, 'reg_lambda': 0.009145011980049581, 'learning_rate': 0.0538067161444542, 'max_depth': 3}. Best is trial 4 with value: 0.9298084731664067.
[I 2026-03-19 17:24:30,480] Trial 6 finished with value: 0.9297869653035704 and parameters: {'min_child_weight': 4, 'subsample': 0.9008725858432424, 'colsample_bytree': 0.767980906708789, 'reg_alpha': 0.0001476698960709839, 'reg_lambda': 0.8900802964318448, 'learning_rate': 0.08048357120308998, 'max_depth': 8}. Best is trial 4 with value: 0.9298084731664067.
[I 2026-03-19 17:24:31,038] Trial 7 finished with value: 0.9278638609819421 and parameters: {'min_child_weight': 9, 'subsample': 0.5273559628927631, 'colsample_bytree': 0.8845842583155148, 'reg_alpha': 2.0953338506957725e-05, 'reg_lambda': 0.25516412995154547, 'learning_rate': 0.033508182735020445, 'max_depth': 8}. Best is trial 4 with value: 0.9298084731664067.
[I 2026-03-19 17:24:31,317] Trial 8 finished with value: 0.9285933474125356 and parameters: {'min_child_weight': 7, 'subsample': 0.6933255319687337, 'colsample_bytree': 0.8246678391235261, 'reg_alpha': 1.5842185020157007, 'reg_lambda': 5.3337792071757194e-08, 'learning_rate': 0.11781058965074975, 'max_depth': 6}. Best is trial 4 with value: 0.9298084731664067.
[I 2026-03-19 17:24:31,648] Trial 9 finished with value: 0.9280875701539908 and parameters: {'min_child_weight': 10, 'subsample': 0.5908750304601431, 'colsample_bytree': 0.6042876694238651, 'reg_alpha': 3.024303273721141e-07, 'reg_lambda': 0.0005032044840915176, 'learning_rate': 0.05799723459448533, 'max_depth': 8}. Best is trial 4 with value: 0.9298084731664067.
[I 2026-03-19 17:24:32,466] Trial 10 finished with value: 0.9304509691963566 and parameters: {'min_child_weight': 2, 'subsample': 0.794247724131805, 'colsample_bytree': 0.6512492658283323, 'reg_alpha': 0.026839255473698063, 'reg_lambda': 7.406645396873992e-07, 'learning_rate': 0.021400985612391656, 'max_depth': 5}. Best is trial 10 with value: 0.9304509691963566.
[I 2026-03-19 17:24:33,214] Trial 11 finished with value: 0.9303216480338251 and parameters: {'min_child_weight': 1, 'subsample': 0.798556035987247, 'colsample_bytree': 0.6349639139039098, 'reg_alpha': 0.027659610933870288, 'reg_lambda': 3.4946055140423694e-07, 'learning_rate': 0.022366354201846354, 'max_depth': 5}. Best is trial 10 with value: 0.9304509691963566.
[I 2026-03-19 17:24:34,319] Trial 12 finished with value: 0.9289748722405549 and parameters: {'min_child_weight': 1, 'subsample': 0.7987116901967162, 'colsample_bytree': 0.9935374908035483, 'reg_alpha': 0.026649223006890578, 'reg_lambda': 2.887074369914888e-06, 'learning_rate': 0.017248392695034524, 'max_depth': 4}. Best is trial 10 with value: 0.9304509691963566.
[I 2026-03-19 17:24:34,893] Trial 13 finished with value: 0.931319229289709 and parameters: {'min_child_weight': 1, 'subsample': 0.7631455102071535, 'colsample_bytree': 0.5174475770011122, 'reg_alpha': 0.11197123119380399, 'reg_lambda': 1.0353413164810204e-08, 'learning_rate': 0.02456921447059443, 'max_depth': 6}. Best is trial 13 with value: 0.931319229289709.
[I 2026-03-19 17:24:35,438] Trial 14 finished with value: 0.9309048262000292 and parameters: {'min_child_weight': 2, 'subsample': 0.6644654965303384, 'colsample_bytree': 0.5083496168609121, 'reg_alpha': 0.32029814611423296, 'reg_lambda': 1.067301130398471e-08, 'learning_rate': 0.03132509056368707, 'max_depth': 7}. Best is trial 13 with value: 0.931319229289709.
[I 2026-03-19 17:24:36,158] Trial 15 finished with value: 0.9275257628578663 and parameters: {'min_child_weight': 2, 'subsample': 0.6407754964306618, 'colsample_bytree': 0.5253577204106303, 'reg_alpha': 9.588205334710723, 'reg_lambda': 1.7848829784170015e-08, 'learning_rate': 0.034247987068324215, 'max_depth': 7}. Best is trial 13 with value: 0.931319229289709.
[I 2026-03-19 17:24:37,430] Trial 16 finished with value: 0.9305798793806175 and parameters: {'min_child_weight': 3, 'subsample': 0.6480200848944543, 'colsample_bytree': 0.5061243344575371, 'reg_alpha': 0.4058802133959517, 'reg_lambda': 8.47943722998893e-06, 'learning_rate': 0.011542102547125415, 'max_depth': 7}. Best is trial 13 with value: 0.931319229289709.
[I 2026-03-19 17:24:37,886] Trial 17 finished with value: 0.9300808147671615 and parameters: {'min_child_weight': 1, 'subsample': 0.5041136607525283, 'colsample_bytree': 0.574586084679293, 'reg_alpha': 0.0021462595021925503, 'reg_lambda': 1.652031248908753e-05, 'learning_rate': 0.0343940429380861, 'max_depth': 7}. Best is trial 13 with value: 0.931319229289709.
[I 2026-03-19 17:24:38,404] Trial 18 finished with value: 0.930477271805685 and parameters: {'min_child_weight': 3, 'subsample': 0.7418259078694216, 'colsample_bytree': 0.5003650795852388, 'reg_alpha': 0.2276870554252028, 'reg_lambda': 1.2709291674082112e-08, 'learning_rate': 0.026371203254213764, 'max_depth': 6}. Best is trial 13 with value: 0.931319229289709.
[I 2026-03-19 17:24:38,565] Trial 19 finished with value: 0.9271188943698168 and parameters: {'min_child_weight': 2, 'subsample': 0.5885807819812525, 'colsample_bytree': 0.5773670881148494, 'reg_alpha': 0.0024121084326699594, 'reg_lambda': 3.814853905393717e-05, 'learning_rate': 0.29987385120881693, 'max_depth': 7}. Best is trial 13 with value: 0.931319229289709.
[I 2026-03-19 17:24:39,437] Trial 20 finished with value: 0.9293588629381987 and parameters: {'min_child_weight': 4, 'subsample': 0.6787896603223335, 'colsample_bytree': 0.9745813665770913, 'reg_alpha': 1.627765565429793e-05, 'reg_lambda': 1.1811678725864146e-07, 'learning_rate': 0.017315277773274573, 'max_depth': 6}. Best is trial 13 with value: 0.931319229289709.
[I 2026-03-19 17:24:40,650] Trial 21 finished with value: 0.9306122096712501 and parameters: {'min_child_weight': 3, 'subsample': 0.6406966344983636, 'colsample_bytree': 0.5051680051361381, 'reg_alpha': 0.40448545262326474, 'reg_lambda': 1.5585166173179604e-05, 'learning_rate': 0.011854820520119057, 'max_depth': 7}. Best is trial 13 with value: 0.931319229289709.
[I 2026-03-19 17:24:41,651] Trial 22 finished with value: 0.9306281008310527 and parameters: {'min_child_weight': 2, 'subsample': 0.5839394949301222, 'colsample_bytree': 0.5535753635491084, 'reg_alpha': 0.24079375931952224, 'reg_lambda': 1.3156986581449242e-07, 'learning_rate': 0.013566889731341748, 'max_depth': 7}. Best is trial 13 with value: 0.931319229289709.
[I 2026-03-19 17:24:42,545] Trial 23 finished with value: 0.9308183837704131 and parameters: {'min_child_weight': 1, 'subsample': 0.5803962707930586, 'colsample_bytree': 0.5711939254798728, 'reg_alpha': 0.22922868940893473, 'reg_lambda': 1.1895953018722078e-07, 'learning_rate': 0.01553537177403304, 'max_depth': 7}. Best is trial 13 with value: 0.931319229289709.
[I 2026-03-19 17:24:42,917] Trial 24 finished with value: 0.9304711071316235 and parameters: {'min_child_weight': 1, 'subsample': 0.5502559081879542, 'colsample_bytree': 0.608398127053716, 'reg_alpha': 0.0027855116982075006, 'reg_lambda': 1.0727757573289905e-08, 'learning_rate': 0.04167191621253386, 'max_depth': 6}. Best is trial 13 with value: 0.931319229289709.
[I 2026-03-19 17:24:44,048] Trial 25 finished with value: 0.9293968099318654 and parameters: {'min_child_weight': 1, 'subsample': 0.682707737422418, 'colsample_bytree': 0.5572742497590024, 'reg_alpha': 5.436587095964558, 'reg_lambda': 6.822836119288863e-08, 'learning_rate': 0.016463078011959006, 'max_depth': 7}. Best is trial 13 with value: 0.931319229289709.
[I 2026-03-19 17:24:44,608] Trial 26 finished with value: 0.9303863086150909 and parameters: {'min_child_weight': 2, 'subsample': 0.739768496961267, 'colsample_bytree': 0.7002562431755579, 'reg_alpha': 0.16478901955121167, 'reg_lambda': 3.6502925410845826e-07, 'learning_rate': 0.025829128806548963, 'max_depth': 6}. Best is trial 13 with value: 0.931319229289709.
[I 2026-03-19 17:24:45,228] Trial 27 finished with value: 0.9307708472837624 and parameters: {'min_child_weight': 1, 'subsample': 0.6099350778314081, 'colsample_bytree': 0.6023803233847667, 'reg_alpha': 1.1873637159839878, 'reg_lambda': 8.25029835820467e-05, 'learning_rate': 0.026624706487832762, 'max_depth': 8}. Best is trial 13 with value: 0.931319229289709.
[I 2026-03-19 17:24:45,736] Trial 28 finished with value: 0.9305261782199051 and parameters: {'min_child_weight': 5, 'subsample': 0.7780913760332745, 'colsample_bytree': 0.5310763321875956, 'reg_alpha': 0.10009205691766256, 'reg_lambda': 4.0934170572966744e-08, 'learning_rate': 0.04199492134899815, 'max_depth': 7}. Best is trial 13 with value: 0.931319229289709.
[I 2026-03-19 17:24:47,444] Trial 29 finished with value: 0.927503981009516 and parameters: {'min_child_weight': 8, 'subsample': 0.7130143270726432, 'colsample_bytree': 0.5554965787836447, 'reg_alpha': 0.010705527266242059, 'reg_lambda': 2.1354198867730227e-07, 'learning_rate': 0.016080595059607867, 'max_depth': 3}. Best is trial 13 with value: 0.931319229289709.
[I 2026-03-19 17:24:48,388] Trial 30 finished with value: 0.9289584331097247 and parameters: {'min_child_weight': 2, 'subsample': 0.766688957758643, 'colsample_bytree': 0.7481182848348735, 'reg_alpha': 0.0007891881447023297, 'reg_lambda': 3.4501948775355103e-06, 'learning_rate': 0.02012947417153318, 'max_depth': 4}. Best is trial 13 with value: 0.931319229289709.
[I 2026-03-19 17:24:48,982] Trial 31 finished with value: 0.9303801439410295 and parameters: {'min_child_weight': 1, 'subsample': 0.6173946126745014, 'colsample_bytree': 0.6079496621715662, 'reg_alpha': 1.744399341452575, 'reg_lambda': 8.883778063105955e-05, 'learning_rate': 0.0283032110916875, 'max_depth': 8}. Best is trial 13 with value: 0.931319229289709.
[I 2026-03-19 17:24:49,344] Trial 32 finished with value: 0.9300451966503627 and parameters: {'min_child_weight': 3, 'subsample': 0.5430297656962616, 'colsample_bytree': 0.5955416764694337, 'reg_alpha': 0.9716530508827668, 'reg_lambda': 0.00011614476646330745, 'learning_rate': 0.043615006082681484, 'max_depth': 8}. Best is trial 13 with value: 0.931319229289709.
[I 2026-03-19 17:24:50,037] Trial 33 finished with value: 0.9307187900361332 and parameters: {'min_child_weight': 1, 'subsample': 0.6159440149958582, 'colsample_bytree': 0.5412083900432851, 'reg_alpha': 0.08088113493235649, 'reg_lambda': 0.13341622092161842, 'learning_rate': 0.029444661925009264, 'max_depth': 8}. Best is trial 13 with value: 0.931319229289709.
[I 2026-03-19 17:24:51,018] Trial 34 finished with value: 0.9317462357130254 and parameters: {'min_child_weight': 2, 'subsample': 0.9608759692780585, 'colsample_bytree': 0.6343429895835034, 'reg_alpha': 0.7447034956619789, 'reg_lambda': 3.1506591797663835e-08, 'learning_rate': 0.014258742182258484, 'max_depth': 7}. Best is trial 34 with value: 0.9317462357130254.
[I 2026-03-19 17:24:51,143] Trial 35 finished with value: 0.9194130517931256 and parameters: {'min_child_weight': 3, 'subsample': 0.962787482207347, 'colsample_bytree': 0.67562322886745, 'reg_alpha': 0.007525378298807575, 'reg_lambda': 2.3975785654909288e-08, 'learning_rate': 0.010017761129760947, 'max_depth': 6}. Best is trial 34 with value: 0.9317462357130254.
[I 2026-03-19 17:24:52,535] Trial 36 finished with value: 0.930950718773597 and parameters: {'min_child_weight': 2, 'subsample': 0.933460572219257, 'colsample_bytree': 0.6338752910551128, 'reg_alpha': 4.652496608971336, 'reg_lambda': 9.923965497862131e-07, 'learning_rate': 0.013829358665247942, 'max_depth': 7}. Best is trial 34 with value: 0.9317462357130254.
[I 2026-03-19 17:24:53,506] Trial 37 finished with value: 0.930565495141141 and parameters: {'min_child_weight': 4, 'subsample': 0.9308239549730959, 'colsample_bytree': 0.7432732461408816, 'reg_alpha': 4.486528817543813, 'reg_lambda': 9.153986296934859e-07, 'learning_rate': 0.0207943051011856, 'max_depth': 6}. Best is trial 34 with value: 0.9317462357130254.
[I 2026-03-19 17:24:54,622] Trial 38 finished with value: 0.9307053647459551 and parameters: {'min_child_weight': 5, 'subsample': 0.8408909816134704, 'colsample_bytree': 0.6594628392604147, 'reg_alpha': 0.06308777220832563, 'reg_lambda': 1.017490990722164e-08, 'learning_rate': 0.012613762235899802, 'max_depth': 7}. Best is trial 34 with value: 0.9317462357130254.
[I 2026-03-19 17:24:55,745] Trial 39 finished with value: 0.9310914103349528 and parameters: {'min_child_weight': 2, 'subsample': 0.9996750597850743, 'colsample_bytree': 0.634833293063814, 'reg_alpha': 0.8098064090578, 'reg_lambda': 3.944055587433919e-08, 'learning_rate': 0.014004838750875234, 'max_depth': 5}. Best is trial 34 with value: 0.9317462357130254.

In [35]:
best_params = study.best_params
best_params

{'min_child_weight': 2,
 'subsample': 0.9608759692780585,
 'colsample_bytree': 0.6343429895835034,
 'reg_alpha': 0.7447034956619789,
 'reg_lambda': 3.1506591797663835e-08,
 'learning_rate': 0.014258742182258484,
 'max_depth': 7}

In [36]:
print(f'ROC AUC score :{study.best_value:.4f}')

ROC AUC score :0.9317

In [37]:
xgb_model = xgb.XGBClassifier(**best_params, random_state=19)

In [38]:
xgb_model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.6343429895835034, device=None,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, feature_types=None, feature_weights=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.014258742182258484,
              max_bin=None, max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=7, max_leaves=None,
              min_child_weight=2, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, ...)

In [40]:
import joblib
joblib.dump(xgb_model, 'xgb_model.joblib')

['xgb_model.joblib']